In [1]:
import pandas as pd

In [17]:
base_df = pd.read_csv("/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/usecase_4_ec_added_entropy.csv")

In [18]:
base_df.columns

Index(['Unnamed: 0', 'NCT Number', 'Study Title', 'Study URL', 'Study Status',
       'Brief Summary', 'Study Results', 'Conditions', 'Interventions',
       'Primary Outcome Measures', 'Secondary Outcome Measures',
       'Other Outcome Measures', 'Sponsor', 'Collaborators', 'Sex', 'Age',
       'Phases', 'Enrollment', 'Funder Type', 'Study Type', 'Study Design',
       'Other IDs', 'Start Date', 'Primary Completion Date', 'Completion Date',
       'First Posted', 'Results First Posted', 'Last Update Posted',
       'Locations', 'Study Recruitment Rate', 'Eligibility Criteria',
       'ec_entropy_1st', 'ec_entropy_2nd'],
      dtype='object')

In [19]:
drop_cols = ['Unnamed: 0', 'Study Title', 'Study URL',
       'Brief Summary', 'Conditions', 'Interventions',
       'Primary Outcome Measures', 'Secondary Outcome Measures',
       'Other Outcome Measures', 'Sponsor', 'Collaborators',
             'Other IDs', 'Start Date', 'Primary Completion Date', 'Completion Date',
       'First Posted', 'Results First Posted', 'Last Update Posted',
       'Locations', 'Eligibility Criteria', 'Study Design', 'Study Type'
             ]

In [20]:
base_df.drop(drop_cols, axis=1, inplace=True)

In [21]:
base_df

,NCT Number,Study Status,Study Results,Sex,Age,Phases,Enrollment,Funder Type,Study Recruitment Rate,ec_entropy_1st,ec_entropy_2nd
0,NCT00900809,COMPLETED,NO,ALL,"ADULT, OLDER_ADULT",PHASE1,7,INDUSTRY,0.551598,4.568732,7.866057
1,NCT01113515,COMPLETED,YES,ALL,"ADULT, OLDER_ADULT",PHASE1|PHASE2,44,INDUSTRY,0.443157,4.667406,7.889543
2,NCT01288573,COMPLETED,NO,ALL,"CHILD, ADULT",PHASE1|PHASE2,46,INDUSTRY,0.044558,4.671892,7.946362
3,NCT01336660,COMPLETED,NO,ALL,CHILD,PHASE2|PHASE3,56,INDUSTRY,7.279202,4.458828,7.200016
4,NCT01376167,COMPLETED,YES,ALL,"CHILD, ADULT, OLDER_ADULT",PHASE2,851,INDUSTRY,1.969008,4.602481,7.957177
...,...,...,...,...,...,...,...,...,...,...,...
20671,NCT04883333,COMPLETED,NO,ALL,"ADULT, OLDER_ADULT",PHASE1,108,INDUSTRY,7.693208,4.586523,7.771016
20672,NCT02453087,COMPLETED,NO,ALL,"ADULT, OLDER_ADULT",PHASE1,66,INDUSTRY,0.199434,4.552530,7.829150
20673,NCT03850587,COMPLETED,NO,ALL,"ADULT, OLDER_ADULT",PHASE2,261,INDUSTRY,1.074256,4.597958,7.863538
20674,NCT01981187,TERMINATED,YES,ALL,"ADULT, OLDER_ADULT",PHASE2,12,INDUSTRY,0.044077,4.481450,7.537349
20675,NCT03591887,COMPLETED,NO,ALL,"ADULT, OLDER_ADULT",PHASE2,108,INDUSTRY,0.133504,4.564661,7.784007

In [15]:
spons_df = pd.read_csv("/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/usecase_4_sponsor_success_added_with_nan.csv")

In [16]:
spons_df.columns

Index(['Unnamed: 0', 'NCT Number', 'Study Title', 'Study URL', 'Study Status',
       'Brief Summary', 'Study Results', 'Conditions', 'Interventions',
       'Primary Outcome Measures', 'Secondary Outcome Measures',
       'Other Outcome Measures', 'Sponsor', 'Collaborators', 'Sex', 'Age',
       'Phases', 'Enrollment', 'Funder Type', 'Study Type', 'Study Design',
       'Other IDs', 'Start Date', 'Primary Completion Date', 'Completion Date',
       'First Posted', 'Results First Posted', 'Last Update Posted',
       'Locations', 'Study Recruitment Rate', 'Eligibility Criteria',
       'sponsor_success_rate'],
      dtype='object')

In [23]:
base_df['sponsor_success_rate'] = spons_df["sponsor_success_rate"]

In [24]:
prev_disease_data = pd.read_csv('/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/usecase_4_prevalent_disease_added.csv')

In [25]:
prev_disease_data.columns

Index(['Unnamed: 0', 'NCT Number', 'Conditions', 'countries', 'mesh_id',
       'Prevalence_disease'],
      dtype='object')

In [27]:
base_df['prevalent_disease'] = prev_disease_data['Prevalence_disease']
base_df['mesh_id'] = prev_disease_data['mesh_id']

In [28]:
popu_df = pd.read_csv('/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/Population_extracted.csv')

In [29]:
popu_df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'NCT Number', 'Locations', 'Cities',
       'no_of_sites', 'population'],
      dtype='object')

In [30]:
base_df['no_of_sites'] = popu_df['no_of_sites']
base_df['population'] = popu_df['population']

In [31]:
comp_df = pd.read_csv('/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/competition.csv')

In [32]:
comp_df.columns

Index(['NCT Number', 'competition'], dtype='object')

In [33]:
base_df['competition'] = comp_df['competition']

In [34]:
study_des = pd.read_csv('/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/after_study_design_new.csv')

In [35]:
study_des.columns

Index(['NCT Number', 'Study Title', 'Study URL', 'Study Status',
       'Brief Summary', 'Study Results', 'Conditions', 'Interventions',
       'Primary Outcome Measures', 'Secondary Outcome Measures',
       'Other Outcome Measures', 'Sponsor', 'Collaborators', 'Sex', 'Age',
       'Enrollment', 'Funder Type', 'Study Type', 'Other IDs', 'Start Date',
       'Primary Completion Date', 'Completion Date', 'First Posted',
       'Results First Posted', 'Last Update Posted', 'Locations',
       'Study Recruitment Rate', 'Allocation_NA', 'Allocation_NON_RANDOMIZED',
       'Allocation_RANDOMIZED', 'Intervention Model_CROSSOVER',
       'Intervention Model_PARALLEL', 'Intervention Model_SEQUENTIAL',
       'Intervention Model_SINGLE_GROUP', 'Masking Complexity_DOUBLE',
       'Masking Complexity_NONE', 'Masking Complexity_QUADRUPLE',
       'Masking Complexity_SINGLE', 'Masking Complexity_TRIPLE',
       'Primary Purpose_BASIC_SCIENCE', 'Primary Purpose_OTHER',
       'Primary Purpose_PREVENTION', 'Primary Purpose_TREATMENT', 'PHASE1',
       'PHASE2', 'PHASE3'],
      dtype='object')

In [36]:
drop_here = ['Study Title', 'Study URL', 'Study Status',
       'Brief Summary', 'Study Results', 'Conditions', 'Interventions',
       'Primary Outcome Measures', 'Secondary Outcome Measures',
       'Other Outcome Measures', 'Sponsor', 'Collaborators', 'Sex', 'Age',
       'Enrollment', 'Funder Type', 'Study Type', 'Other IDs', 'Start Date',
       'Primary Completion Date', 'Completion Date', 'First Posted',
       'Results First Posted', 'Last Update Posted', 'Locations',
       'Study Recruitment Rate']

study_des.drop(drop_here, axis=1, inplace=True)

In [37]:
study_des.columns

Index(['NCT Number', 'Allocation_NA', 'Allocation_NON_RANDOMIZED',
       'Allocation_RANDOMIZED', 'Intervention Model_CROSSOVER',
       'Intervention Model_PARALLEL', 'Intervention Model_SEQUENTIAL',
       'Intervention Model_SINGLE_GROUP', 'Masking Complexity_DOUBLE',
       'Masking Complexity_NONE', 'Masking Complexity_QUADRUPLE',
       'Masking Complexity_SINGLE', 'Masking Complexity_TRIPLE',
       'Primary Purpose_BASIC_SCIENCE', 'Primary Purpose_OTHER',
       'Primary Purpose_PREVENTION', 'Primary Purpose_TREATMENT', 'PHASE1',
       'PHASE2', 'PHASE3'],
      dtype='object')

In [38]:
# merge base_df and study_des on 'NCT Number' column
base_df = pd.merge(base_df, study_des, on='NCT Number', how='left')

In [40]:
base_df.columns

Index(['NCT Number', 'Study Status', 'Study Results', 'Sex', 'Age', 'Phases',
       'Enrollment', 'Funder Type', 'Study Recruitment Rate', 'ec_entropy_1st',
       'ec_entropy_2nd', 'sponsor_success_rate', 'prevalent_disease',
       'mesh_id', 'no_of_sites', 'population', 'competition', 'Allocation_NA',
       'Allocation_NON_RANDOMIZED', 'Allocation_RANDOMIZED',
       'Intervention Model_CROSSOVER', 'Intervention Model_PARALLEL',
       'Intervention Model_SEQUENTIAL', 'Intervention Model_SINGLE_GROUP',
       'Masking Complexity_DOUBLE', 'Masking Complexity_NONE',
       'Masking Complexity_QUADRUPLE', 'Masking Complexity_SINGLE',
       'Masking Complexity_TRIPLE', 'Primary Purpose_BASIC_SCIENCE',
       'Primary Purpose_OTHER', 'Primary Purpose_PREVENTION',
       'Primary Purpose_TREATMENT', 'PHASE1', 'PHASE2', 'PHASE3'],
      dtype='object')

In [41]:
dura_df = pd.read_csv('/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/duration.csv')

In [42]:
dura_df.columns

Index(['NCT Number', 'duration'], dtype='object')

In [43]:
base_df['study_duration'] = dura_df['duration']

In [44]:
base_df.columns

Index(['NCT Number', 'Study Status', 'Study Results', 'Sex', 'Age', 'Phases',
       'Enrollment', 'Funder Type', 'Study Recruitment Rate', 'ec_entropy_1st',
       'ec_entropy_2nd', 'sponsor_success_rate', 'prevalent_disease',
       'mesh_id', 'no_of_sites', 'population', 'competition', 'Allocation_NA',
       'Allocation_NON_RANDOMIZED', 'Allocation_RANDOMIZED',
       'Intervention Model_CROSSOVER', 'Intervention Model_PARALLEL',
       'Intervention Model_SEQUENTIAL', 'Intervention Model_SINGLE_GROUP',
       'Masking Complexity_DOUBLE', 'Masking Complexity_NONE',
       'Masking Complexity_QUADRUPLE', 'Masking Complexity_SINGLE',
       'Masking Complexity_TRIPLE', 'Primary Purpose_BASIC_SCIENCE',
       'Primary Purpose_OTHER', 'Primary Purpose_PREVENTION',
       'Primary Purpose_TREATMENT', 'PHASE1', 'PHASE2', 'PHASE3',
       'study_duration'],
      dtype='object')

In [47]:
one_hot_cols = ['Study Status', 'Study Results', 'Sex', 'Funder Type']

final_df = pd.get_dummies(base_df, columns=one_hot_cols, dtype=int)

In [49]:
final_df.columns

Index(['NCT Number', 'Age', 'Phases', 'Enrollment', 'Study Recruitment Rate',
       'ec_entropy_1st', 'ec_entropy_2nd', 'sponsor_success_rate',
       'prevalent_disease', 'mesh_id', 'no_of_sites', 'population',
       'competition', 'Allocation_NA', 'Allocation_NON_RANDOMIZED',
       'Allocation_RANDOMIZED', 'Intervention Model_CROSSOVER',
       'Intervention Model_PARALLEL', 'Intervention Model_SEQUENTIAL',
       'Intervention Model_SINGLE_GROUP', 'Masking Complexity_DOUBLE',
       'Masking Complexity_NONE', 'Masking Complexity_QUADRUPLE',
       'Masking Complexity_SINGLE', 'Masking Complexity_TRIPLE',
       'Primary Purpose_BASIC_SCIENCE', 'Primary Purpose_OTHER',
       'Primary Purpose_PREVENTION', 'Primary Purpose_TREATMENT', 'PHASE1',
       'PHASE2', 'PHASE3', 'study_duration',
       'Study Status_ACTIVE_NOT_RECRUITING', 'Study Status_COMPLETED',
       'Study Status_ENROLLING_BY_INVITATION',
       'Study Status_NOT_YET_RECRUITING', 'Study Status_RECRUITING',
       'Study Status_SUSPENDED', 'Study Status_TERMINATED',
       'Study Status_UNKNOWN', 'Study Results_NO', 'Study Results_YES',
       'Sex_ALL', 'Sex_FEMALE', 'Sex_MALE', 'Funder Type_FED',
       'Funder Type_INDIV', 'Funder Type_INDUSTRY', 'Funder Type_NETWORK',
       'Funder Type_NIH', 'Funder Type_OTHER', 'Funder Type_OTHER_GOV',
       'Funder Type_UNKNOWN'],
      dtype='object')

In [50]:
final_df.drop('Phases', axis=1, inplace=True)

In [51]:
final_df.columns

Index(['NCT Number', 'Age', 'Enrollment', 'Study Recruitment Rate',
       'ec_entropy_1st', 'ec_entropy_2nd', 'sponsor_success_rate',
       'prevalent_disease', 'mesh_id', 'no_of_sites', 'population',
       'competition', 'Allocation_NA', 'Allocation_NON_RANDOMIZED',
       'Allocation_RANDOMIZED', 'Intervention Model_CROSSOVER',
       'Intervention Model_PARALLEL', 'Intervention Model_SEQUENTIAL',
       'Intervention Model_SINGLE_GROUP', 'Masking Complexity_DOUBLE',
       'Masking Complexity_NONE', 'Masking Complexity_QUADRUPLE',
       'Masking Complexity_SINGLE', 'Masking Complexity_TRIPLE',
       'Primary Purpose_BASIC_SCIENCE', 'Primary Purpose_OTHER',
       'Primary Purpose_PREVENTION', 'Primary Purpose_TREATMENT', 'PHASE1',
       'PHASE2', 'PHASE3', 'study_duration',
       'Study Status_ACTIVE_NOT_RECRUITING', 'Study Status_COMPLETED',
       'Study Status_ENROLLING_BY_INVITATION',
       'Study Status_NOT_YET_RECRUITING', 'Study Status_RECRUITING',
       'Study Status_SUSPENDED', 'Study Status_TERMINATED',
       'Study Status_UNKNOWN', 'Study Results_NO', 'Study Results_YES',
       'Sex_ALL', 'Sex_FEMALE', 'Sex_MALE', 'Funder Type_FED',
       'Funder Type_INDIV', 'Funder Type_INDUSTRY', 'Funder Type_NETWORK',
       'Funder Type_NIH', 'Funder Type_OTHER', 'Funder Type_OTHER_GOV',
       'Funder Type_UNKNOWN'],
      dtype='object')

In [54]:
final_df['Enrollment'].sort_values()

9154          1
13330         1
13087         1
5942          1
13012         1
          ...
13681     44247
13540     44325
18591     46169
12744     47079
15422    477102
Name: Enrollment, Length: 20676, dtype: int64

In [55]:
# remove the row with max Enrollment value
final_df = final_df[final_df['Enrollment'] != final_df['Enrollment'].max()]

In [57]:
final_df['Enrollment'].sort_values()

9154         1
13330        1
13087        1
5942         1
13012        1
         ...
14405    39680
13681    44247
13540    44325
18591    46169
12744    47079
Name: Enrollment, Length: 20675, dtype: int64

In [60]:
final_df.columns

Index(['NCT Number', 'Age', 'Enrollment', 'Study Recruitment Rate',
       'ec_entropy_1st', 'ec_entropy_2nd', 'sponsor_success_rate',
       'prevalent_disease', 'mesh_id', 'no_of_sites', 'population',
       'competition', 'Allocation_NA', 'Allocation_NON_RANDOMIZED',
       'Allocation_RANDOMIZED', 'Intervention Model_CROSSOVER',
       'Intervention Model_PARALLEL', 'Intervention Model_SEQUENTIAL',
       'Intervention Model_SINGLE_GROUP', 'Masking Complexity_DOUBLE',
       'Masking Complexity_NONE', 'Masking Complexity_QUADRUPLE',
       'Masking Complexity_SINGLE', 'Masking Complexity_TRIPLE',
       'Primary Purpose_BASIC_SCIENCE', 'Primary Purpose_OTHER',
       'Primary Purpose_PREVENTION', 'Primary Purpose_TREATMENT', 'PHASE1',
       'PHASE2', 'PHASE3', 'study_duration',
       'Study Status_ACTIVE_NOT_RECRUITING', 'Study Status_COMPLETED',
       'Study Status_ENROLLING_BY_INVITATION',
       'Study Status_NOT_YET_RECRUITING', 'Study Status_RECRUITING',
       'Study Status_SUSPENDED', 'Study Status_TERMINATED',
       'Study Status_UNKNOWN', 'Study Results_NO', 'Study Results_YES',
       'Sex_ALL', 'Sex_FEMALE', 'Sex_MALE', 'Funder Type_FED',
       'Funder Type_INDIV', 'Funder Type_INDUSTRY', 'Funder Type_NETWORK',
       'Funder Type_NIH', 'Funder Type_OTHER', 'Funder Type_OTHER_GOV',
       'Funder Type_UNKNOWN'],
      dtype='object')

In [61]:
nan_list = ['Allocation_NA', 'Allocation_NON_RANDOMIZED',
       'Allocation_RANDOMIZED', 'Intervention Model_CROSSOVER',
       'Intervention Model_PARALLEL', 'Intervention Model_SEQUENTIAL',
       'Intervention Model_SINGLE_GROUP', 'Masking Complexity_DOUBLE',
       'Masking Complexity_NONE', 'Masking Complexity_QUADRUPLE',
       'Masking Complexity_SINGLE', 'Masking Complexity_TRIPLE',
       'Primary Purpose_BASIC_SCIENCE', 'Primary Purpose_OTHER',
       'Primary Purpose_PREVENTION', 'Primary Purpose_TREATMENT']

final_df[nan_list] = final_df[nan_list].fillna(0)

<ipython-input-61-1e691bd6a0db>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[nan_list] = final_df[nan_list].fillna(0)

In [69]:
columns_to_fill = ['sponsor_success_rate', 'prevalent_disease', 'population']
final_df[columns_to_fill] = final_df[columns_to_fill].apply(lambda col: col.fillna(col.mean()))

<ipython-input-69-0243beba6f38>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[columns_to_fill] = final_df[columns_to_fill].apply(lambda col: col.fillna(col.mean()))

In [70]:
final_df.isna().sum()

NCT Number                              0
Age                                     0
Enrollment                              0
Study Recruitment Rate                  0
ec_entropy_1st                          0
ec_entropy_2nd                          0
sponsor_success_rate                    0
prevalent_disease                       0
mesh_id                                 0
no_of_sites                             0
population                              0
competition                             0
Allocation_NA                           0
Allocation_NON_RANDOMIZED               0
Allocation_RANDOMIZED                   0
Intervention Model_CROSSOVER            0
Intervention Model_PARALLEL             0
Intervention Model_SEQUENTIAL           0
Intervention Model_SINGLE_GROUP         0
Masking Complexity_DOUBLE               0
Masking Complexity_NONE                 0
Masking Complexity_QUADRUPLE            0
Masking Complexity_SINGLE               0
Masking Complexity_TRIPLE               0
Primary Purpose_BASIC_SCIENCE           0
Primary Purpose_OTHER                   0
Primary Purpose_PREVENTION              0
Primary Purpose_TREATMENT               0
PHASE1                                  0
PHASE2                                  0
PHASE3                                  0
study_duration                          0
Study Status_ACTIVE_NOT_RECRUITING      0
Study Status_COMPLETED                  0
Study Status_ENROLLING_BY_INVITATION    0
Study Status_NOT_YET_RECRUITING         0
Study Status_RECRUITING                 0
Study Status_SUSPENDED                  0
Study Status_TERMINATED                 0
Study Status_UNKNOWN                    0
Study Results_NO                        0
Study Results_YES                       0
Sex_ALL                                 0
Sex_FEMALE                              0
Sex_MALE                                0
Funder Type_FED                         0
Funder Type_INDIV                       0
Funder Type_INDUSTRY                    0
Funder Type_NETWORK                     0
Funder Type_NIH                         0
Funder Type_OTHER                       0
Funder Type_OTHER_GOV                   0
Funder Type_UNKNOWN                     0
dtype: int64

In [72]:
final_df.columns

Index(['NCT Number', 'Age', 'Enrollment', 'Study Recruitment Rate',
       'ec_entropy_1st', 'ec_entropy_2nd', 'sponsor_success_rate',
       'prevalent_disease', 'mesh_id', 'no_of_sites', 'population',
       'competition', 'Allocation_NA', 'Allocation_NON_RANDOMIZED',
       'Allocation_RANDOMIZED', 'Intervention Model_CROSSOVER',
       'Intervention Model_PARALLEL', 'Intervention Model_SEQUENTIAL',
       'Intervention Model_SINGLE_GROUP', 'Masking Complexity_DOUBLE',
       'Masking Complexity_NONE', 'Masking Complexity_QUADRUPLE',
       'Masking Complexity_SINGLE', 'Masking Complexity_TRIPLE',
       'Primary Purpose_BASIC_SCIENCE', 'Primary Purpose_OTHER',
       'Primary Purpose_PREVENTION', 'Primary Purpose_TREATMENT', 'PHASE1',
       'PHASE2', 'PHASE3', 'study_duration',
       'Study Status_ACTIVE_NOT_RECRUITING', 'Study Status_COMPLETED',
       'Study Status_ENROLLING_BY_INVITATION',
       'Study Status_NOT_YET_RECRUITING', 'Study Status_RECRUITING',
       'Study Status_SUSPENDED', 'Study Status_TERMINATED',
       'Study Status_UNKNOWN', 'Study Results_NO', 'Study Results_YES',
       'Sex_ALL', 'Sex_FEMALE', 'Sex_MALE', 'Funder Type_FED',
       'Funder Type_INDIV', 'Funder Type_INDUSTRY', 'Funder Type_NETWORK',
       'Funder Type_NIH', 'Funder Type_OTHER', 'Funder Type_OTHER_GOV',
       'Funder Type_UNKNOWN'],
      dtype='object')

In [71]:
final_df.describe()

,Enrollment,Study Recruitment Rate,ec_entropy_1st,ec_entropy_2nd,sponsor_success_rate,prevalent_disease,no_of_sites,population,competition,Allocation_NA,...,Sex_FEMALE,Sex_MALE,Funder Type_FED,Funder Type_INDIV,Funder Type_INDUSTRY,Funder Type_NETWORK,Funder Type_NIH,Funder Type_OTHER,Funder Type_OTHER_GOV,Funder Type_UNKNOWN
count,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,2.067400e+04,20674.000000,20674.000000,...,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.00000,20674.000000
mean,212.217761,6.622338,4.600629,7.767215,0.406903,6312.284117,17.944858,2.885335e+07,29.751620,0.225839,...,0.045371,0.077585,0.000435,0.000242,0.886186,0.002177,0.002660,0.106172,0.00208,0.000048
std,1221.477731,46.942730,0.096542,0.254177,0.203724,32392.039100,46.885308,7.337049e+07,76.774484,0.418144,...,0.208122,0.267524,0.020861,0.015550,0.317593,0.046605,0.051511,0.308065,0.04556,0.006955
min,1.000000,0.001128,4.096691,5.058814,0.000000,0.000000,1.000000,0.000000e+00,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,23.000000,0.169635,4.538214,7.647186,0.363636,0.000000,1.000000,1.606390e+05,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,48.000000,0.829709,4.597664,7.807252,0.406903,78.200000,2.000000,5.325616e+06,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000
75%,134.750000,5.246977,4.658289,7.939453,0.473361,6312.284117,15.000000,2.431929e+07,18.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000
max,47079.000000,4816.602871,5.311990,8.395052,1.000000,317695.200000,1332.000000,1.689211e+09,458.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [73]:
numerical_cols = ['Enrollment', 'ec_entropy_1st', 'ec_entropy_2nd', 'sponsor_success_rate',
       'prevalent_disease', 'no_of_sites', 'population',
       'competition']

# Apply Min-Max Scaling
final_df[numerical_cols] = final_df[numerical_cols].apply(lambda col: (col - col.min()) / (col.max() - col.min()))

<ipython-input-73-dcbd42622ef3>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[numerical_cols] = final_df[numerical_cols].apply(lambda col: (col - col.min()) / (col.max() - col.min()))

In [74]:
final_df.describe()

,Enrollment,Study Recruitment Rate,ec_entropy_1st,ec_entropy_2nd,sponsor_success_rate,prevalent_disease,no_of_sites,population,competition,Allocation_NA,...,Sex_FEMALE,Sex_MALE,Funder Type_FED,Funder Type_INDIV,Funder Type_INDUSTRY,Funder Type_NETWORK,Funder Type_NIH,Funder Type_OTHER,Funder Type_OTHER_GOV,Funder Type_UNKNOWN
count,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,...,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.000000,20674.00000,20674.000000
mean,0.004487,6.622338,0.414662,0.811813,0.406903,0.019869,0.012731,0.017081,0.064960,0.225839,...,0.045371,0.077585,0.000435,0.000242,0.886186,0.002177,0.002660,0.106172,0.00208,0.000048
std,0.025946,46.942730,0.079439,0.076187,0.203724,0.101959,0.035226,0.043435,0.167630,0.418144,...,0.208122,0.267524,0.020861,0.015550,0.317593,0.046605,0.051511,0.308065,0.04556,0.006955
min,0.000000,0.001128,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,0.000467,0.169635,0.363304,0.775836,0.363636,0.000000,0.000000,0.000095,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,0.000998,0.829709,0.412222,0.823814,0.406903,0.000246,0.000751,0.003153,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000
75%,0.002841,5.246977,0.462107,0.863439,0.473361,0.019869,0.010518,0.014397,0.039301,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000
max,1.000000,4816.602871,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [90]:
final_df['mesh_id'] = final_df['mesh_id'].apply(lambda x: eval(x))

<ipython-input-90-7c1bdd7110e0>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['mesh_id'] = final_df['mesh_id'].apply(lambda x: eval(x))

In [96]:
freq_dict = {}
for sub_list in final_df['mesh_id']:
  for item in sub_list:
    if item in freq_dict:
      freq_dict[item] += 1
    else:
      freq_dict[item] = 1

In [97]:
# Frequency encoding: Replace each list with the sum of frequencies of its elements
for index, row in final_df.iterrows():
    freq_sum = sum(freq_dict[item] for item in row['mesh_id'])/len(row['mesh_id'])
    final_df.at[index, 'mesh_id_encoded'] = freq_sum

<ipython-input-97-679ff4ef65da>:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '126.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  final_df.at[index, 'mesh_id_encoded'] = freq_sum

In [98]:
final_df['mesh_id_encoded']

0        1686.0
1        1471.0
2        1686.0
3         126.5
4         111.0
          ...
20671    3018.0
20672    2909.0
20673     487.0
20674     550.0
20675    1875.0
Name: mesh_id_encoded, Length: 20674, dtype: float64

In [99]:
numerical_cols = ['mesh_id_encoded']

# Apply Min-Max Scaling
final_df[numerical_cols] = final_df[numerical_cols].apply(lambda col: (col - col.min()) / (col.max() - col.min()))

<ipython-input-99-dd86a7bd165a>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df[numerical_cols] = final_df[numerical_cols].apply(lambda col: (col - col.min()) / (col.max() - col.min()))

In [100]:
final_dataset = final_df.drop('mesh_id', axis=1)

In [102]:
one_hot_cols = ['Age']

final_dataset = pd.get_dummies(final_dataset, columns=one_hot_cols, dtype=int)

In [103]:
final_dataset.to_csv('/content/drive/MyDrive/NOVARTIS NEST - BioLogits/Data/final_final_dataset.csv', index=False)